kind: pipeline
name: chainflip-eth-contracts
type: docker

steps:
  - name: test
    image: docker.pkg.github.com/sambacha/brownie-ci-docker/pyownie:latest
    commands:
      - brownie test
trigger:
  event:
    - push
image_pull_secrets:
  - dockerconfigjson
