kind: secret
name: docker_username
get:
  path: repo-secret
  name: docker_username
---
kind: secret
name: docker_password
get:
  path: repo-secret
  name: docker_password
---
kind: secret
name: discord_webhook_id
get:
  path: repo-secret
  name: discord_webhook_id
---
kind: secret
name: discord_webhook_token
get:
  path: repo-secret
  name: discord_webhook_token
---
kind: secret
name: dockerconfigjson
get:
  path: dockerconfigjson
  name: .dockerconfigjson
---
kind: pipeline
name: chainflip-eth-contracts
type: kubernetes

steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ghcr.io/chainflip-io/chainflip-eth-contracts/eth-brownie
      dockerfile: Dockerfile.eth-brownie
      registry: ghcr.io
      tags: latest
      cache_from: ghcr.io/chainflip-io/chainflip-eth-contracts/eth-brownie:latest

  - name: test
    pull: always
    image: ghcr.io/chainflip-io/chainflip-eth-contracts/eth-brownie:latest
    commands:
      - /home/circleci/.poetry/bin/poetry install
      - brownie pm install OpenZeppelin/openzeppelin-contracts@4.0.0
      - /home/circleci/.poetry/bin/poetry run brownie test --stateful false --network mainnet-fork

trigger:
  event:
    - pull_request

image_pull_secrets:
  - dockerconfigjson

node_selector:
  type: ci

tolerations:
  - key: "workloadKind"
    operator: "Equal"
    value: "ci"

---
kind: pipeline
name: chainflip-eth-contracts-nightly-stateful
type: kubernetes

steps:
  - name: test
    pull: always
    image: ghcr.io/chainflip-io/chainflip-eth-contracts/eth-brownie:latest
    commands:
      - /home/circleci/.poetry/bin/poetry install
      - brownie pm install OpenZeppelin/openzeppelin-contracts@4.0.0
      - >
        /home/circleci/.poetry/bin/poetry run brownie test ./tests/stateful/test_keyManager.py --network mainnet-fork
        && /home/circleci/.poetry/bin/poetry run brownie test ./tests/stateful/test_vault.py --network mainnet-fork
        && /home/circleci/.poetry/bin/poetry run brownie test ./tests/stateful/test_stakeManager.py --network mainnet-fork
        && /home/circleci/.poetry/bin/poetry run brownie test ./tests/stateful/test_all.py --network mainnet-fork
  - name: notify
    image: appleboy/drone-discord
    when:
      status:
        - failure
    settings:
      avatar_url: https://png2.cleanpng.com/sh/809888174adf1a2f743a77fa1d63b2c9/L0KzQYm3VsE4N6dmkZH0aYP2gLBuTgNifaN0hp99aHWwfLF5hL1wbl55gNc2cnnxd8S0hglmNaVtfZ98aXzwccPwjPxqd58yTdQ7NnW4RbK3gcA2a2IzSaM9OUe6RYe4VcI6Omg6T6UDMES0QXB3jvc=/kisspng-sauron-the-lord-of-the-rings-eye-the-silmarillion-5b26e55a0a05c1.1149775615292757380411.png
      username: Sauron
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      message: >
        ⚠️ Stateful tests have failed ⚠️

        The nightly test job was unsuccessful.
        Logs: {{build.link}}
        Duration: `{{since build.started}}`
        Responsible parties: <@705248954073219142>



image_pull_secrets:
  - dockerconfigjson

trigger:
  event:
    - cron
  cron:
    - nightly

node_selector:
  type: ci

tolerations:
  - key: "workloadKind"
    operator: "Equal"
    value: "ci"