kind: pipeline
name: chainflip-eth-contracts
type: docker

steps:
  - name: build
    image: docker
    commands:
      - docker pull docker.pkg.github.com/sambacha/brownie-ci-docker/pyownie:latest
      - docker tag docker.pkg.github.com/sambacha/brownie-ci-docker/pyownie:latest ghcr.io/chainflip-io/eth-brownie:latest
      - docker push ghcr.io/chainflip-io/eth-brownie:latest
  - name: test
    image: ghcr.io/chainflip-io/eth-brownie
    commands:
      - brownie test
trigger:
  event:
    - push
image_pull_secrets:
  - dockerconfigjson
