kind: pipeline
name: chainflip-eth-contracts
type: docker

steps:
  - name: test
    image: http://ghcr.io/chainflip-io/eth-brownie:latest
    commands:
      - brownie test
trigger:
  event:
    - push
image_pull_secrets:
  - dockerconfigjson
