kind: pipeline
name: chainflip-eth-contracts
type: docker

clone:
  disable: true
steps:
  - name: test
    image: ghcr.io/chainflip-io/eth-brownie:latest
    commands:
      - git clone https://github.com/chainflip-io/chainflip-eth-contracts.git
      - cd chainflip-eth-contracts
      - poetry install
      - brownie test
trigger:
  event:
    - push
image_pull_secrets:
  - dockerconfigjson
