kind: pipeline
name: chainflip-eth-contracts
type: docker

clone:
  disable: true
steps:
  - name: test
    image: python:rc-buster
    commands:
      - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      - pip install eth-brownie
      - cd /tmp
      - git clone https://github.com/chainflip-io/chainflip-eth-contracts.git
      - cd chainflip-eth-contracts
      - poetry install
      - brownie test
trigger:
  event:
    - push
image_pull_secrets:
  - dockerconfigjson
