kind: pipeline
name: chainflip-eth-contracts
type: docker

steps:
  - name: build
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ghcr.io/chainflip-io/eth-brownie
      registry: ghcr.io
      tags: latest
      cache_from: ghcr.io/chainflip-io/eth-brownie
  - name: test
    image: ghcr.io/chainflip-io/eth-brownie
    commands:
      - brownie test
trigger:
  event:
    - push
image_pull_secrets:
  - dockerconfigjson
