version: "3.9"
services:
  init:
    image: ghcr.io/chainflip-io/chainflip-eth-contracts/localnet-initial-state:${IMAGE_TAG}
    container_name: init
    platform: linux/amd64
    volumes:
      - "/tmp/chainflip/data:/localnet-initial-state"
    command: /bin/sh -c "cp -R /initial-state/* /localnet-initial-state"

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    volumes:
      - "/tmp/chainflip/data/redis-data:/data"

  geth:
    image: ghcr.io/chainflip-io/chainflip-eth-contracts/geth:${IMAGE_TAG}
    container_name: geth
    platform: linux/amd64
    ports:
      - "8545:8545"
      - "8551:8551"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - "/tmp/chainflip/data/l1data:/datadir"
      - "/tmp/chainflip/data/l1keystore:/keystore"
      - "/tmp/chainflip/data/config:/config"

  sequencer:
    image: offchainlabs/nitro-node:v2.0.14-2baa834-dev
    user: root
    platform: linux/amd64
    ports:
      - "8547:8547"
      - "8548:8548"
      - "9642:9642"
    volumes:
      - "/tmp/chainflip/data/seqdata:/home/user/.arbitrum/local/nitro"
      - "/tmp/chainflip/data/config:/config"
    command: --conf.file /config/sequencer_config.json --node.feed.output.enable --node.feed.output.port 9642  --http.api net,web3,eth,txpool,debug --node.seq-coordinator.my-url  ws://sequencer:8548 --graphql.enable --graphql.vhosts * --graphql.corsdomain *
    depends_on:
      - geth
      - redis

  staker-unsafe:
    image: offchainlabs/nitro-node:v2.0.14-2baa834-dev
    user: root
    platform: linux/amd64
    ports:
      - "8047:8547"
      - "8048:8548"
    volumes:
      - "/tmp/chainflip/data/unsafestaker-data:/home/user/.arbitrum/local/nitro"
      - "/tmp/chainflip/data/l1keystore:/home/user/l1keystore"
      - "/tmp/chainflip/data/config:/config"
    command: --conf.file /config/unsafe_staker_config.json
    depends_on:
      - sequencer
      - redis

  poster:
    image: offchainlabs/nitro-node:v2.0.14-2baa834-dev
    user: root
    platform: linux/amd64
    ports:
      - "8147:8547"
      - "8148:8548"
    volumes:
      - "/tmp/chainflip/data/poster-data:/home/user/.arbitrum/local/nitro"
      - "/tmp/chainflip/data/l1keystore:/home/user/l1keystore"
      - "/tmp/chainflip/data/config:/config"
    command: --conf.file /config/poster_config.json
    depends_on:
      - geth
      - redis
