FROM cimg/python:3.10.0-node

USER root

RUN apt-get update -y \
    && apt-get install curl

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - && chown -R root:root /root

RUN curl -fsSL https://deb.nodesource.com/setup_14.x | sh - \
    && apt-get install -y nodejs

RUN npm install --global ganache-cli \
    && ganache-cli --version

ENV PATH="/root/.poetry/bin:${PATH}"
