// autogenerated by brownie
// do not modify the existing settings
module.exports = {
  networks: {
    hardhat: {
      chainId: Number(process.env.HH_CHAIN_ID) || 31337,
      hardfork: "shanghai",
      // base fee of 0 allows use of 0 gas price when testing
      initialBaseFeePerGas: 1000000000,
      // brownie expects calls and transactions to throw on revert
      throwOnTransactionFailures: true,
      throwOnCallFailures: true,
    },
  },
};
