// Hardhat node config for the `make deploy-{eth,arb,bsc}` targets: a throwaway
// localnet whose chain id is set via HH_CHAIN_ID so `deploy_contracts` takes the
// right code path (eth 10997 / arb 412346 / bsc 343). Same core settings as the
// brownie-autogenerated hardhat.config.js. The default mnemonic ("test test ... junk")
// matches the default SEED, so the deployer/accounts are pre-funded.
module.exports = {
  networks: {
    hardhat: {
      chainId: Number(process.env.HH_CHAIN_ID) || 31337,
      hardfork: "shanghai",
      // base fee 0 so the deploy's 0-gas-price txs are valid, matching the geth/nitro
      // localnets the contracts are actually deployed against in CI.
      initialBaseFeePerGas: 0,
      // Mine on each tx (fast) AND every second, so brownie's required_confs (3 for
      // bnb_localnet) is always satisfied even after the final deploy tx.
      mining: {
        auto: true,
        interval: 1000,
      },
      // brownie expects calls and transactions to throw on revert
      throwOnTransactionFailures: true,
      throwOnCallFailures: true,
    },
  },
};
