live:
# - name: Ethereum
#   networks:
#   - chainid: 1
#     explorer: https://api.etherscan.io/api
#     host: https://eth-mainnet.alchemyapi.io/v2/$WEB3_ALCHEMY_PROJECT_ID
#     id: mainnet-alchemy
#     multicall2: '0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696'
#     name: Mainnet (alchemy)

# - name: Ethereum
#   networks:
#   - chainid: 4
#     explorer: https://api-rinkeby.etherscan.io/
#     host: https://eth-rinkeby.alchemyapi.io/v2/$WEB3_ALCHEMY_PROJECT_ID
#     id: rinkeby-alchemy
#     multicall2: '0x5ba1e12693dc8f9c48aad8770482f4739beed696'
#     name: Rinkeby (alchemy)

- name: Ethereum
  networks:
  - chainid: 10997
    host: $RPC_URL
    id: ibiza-swapping-testnet
    name: ibiza-swapping (private)  
