version: "3.8"

services:
  geth:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    pull_policy: always
    container_name: geth_base_image
    restart: unless-stopped
    ports:
      - 30303:30303
      - 30303:30303/udp
      - 8545:8545
      - 8546:8546
      - 8551:8551
    stop_signal: SIGINT
    stop_grace_period: 2m
    healthcheck:
      test: ["CMD-SHELL", "echo hi"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:

