name: Run on GH Ubuntu
on: push

jobs:
  run-all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: npm
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9.7'
    - uses: snok/install-poetry@v1
    - run: npm install --global ganache-cli
    - run: npm install
    - run: poetry install --quiet
    - run: poetry run brownie pm install OpenZeppelin/openzeppelin-contracts@4.0.0
    - run: poetry run brownie test --network hardhat --stateful false